### ISSUE TITLE
How to read daily production?

### ISSUE THREAD

**Issue by spleijers** [kloknibor/MasterVoltXS#1]
First of all, thank you so much for this custom component!! It works great on a Mastervolt XS4300! Better than my old solution of reading the inverter with a php script (https://github.com/kriegsmanj/mastervolt-php). Only one thing i am missing; how can i read the current day production? 
The php script i used can do this with $MasterVolt->getDayTotal($day). Is there a way to do this with this component?

Another great addition would be to include a prefix for the sensors; like sensor.**xs4300_**spac_solar

I did have some struggles to setup a serial server. If someone needs info on how to setup a raspberry pi as a serial server;

1. Install ser2net (sudo apt install ser2net -y)
2. Open the config: sudo nano /etc/ser2net.conf
3. Insert line; 3000:raw:0:/dev/ttySC0:9600 8DATABITS NONE 1STOPBIT  (where /dev/ttySC0 is your inverter connection)
4. Restart ser2net
5. Done (maybe make sure that ser2net runs after a reboot)

Then setup this custom component:

```sensor:
  - platform: MasterVoltXS
    TCP_PORT: 3000
    TCP_IP: 192.168.1.173 (your raspberry ip)
    RECONNECT_INTERVAL: 60

**Comment by kloknibor** [comment]
The underlaying package XSsolar supports the daily totals, at the moment I don't feel the need to implement it due to the energy monitor window. If you do still want it feel free to contribute.
