### ISSUE TITLE
How to correctly integrate?

### ISSUE THREAD

**Issue by PurpleBlueNL** [kloknibor/MasterVoltXS#2]
Hi, 

Please can you update the instructions to install?

In readme file:
"_To install this sensor add the MasterVolt.py file to the this add the following to your configuration.yaml :_"
But I can't find the **MasterVolt.py** file?

When i copy the rest to Home Assistant:  

This is what I see in the Logfile:
"2021-09-21 12:35:55 ERROR (MainThread) [custom_components.MasterVoltXS.sensor] Creating energy thingyZ"
**
Deze fout is ontstaan door een aangepaste integratie**
```
Logger: custom_components.MasterVoltXS.sensor
Source: custom_components/MasterVoltXS/sensor.py:270
Integration: MasterVoltXS
First occurred: 21 september 2021 12:35:55 (1 occurrences)
Last logged: 21 september 2021 12:35:55
```
Please could you assist/help?

**Comment by PurpleBlueNL** [comment]
It't not very clear to start with, but it works for now!

**Comment by muppet99** [comment]
Hi PurpleBlueNL,

You can put line 275 in a comment, so the error does not appear anymore. It will only show at a reboot of HA, because then a log entry is created. 

So as easy as a #
