### ISSUE TITLE
Due to HA update to higher python version, loop function breaks

### ISSUE THREAD

**Issue by muppet99** [kloknibor/MasterVoltXS#4]
Hi Robin,

Due to an update of HA, migrating to newer python version, the loop function seems to be broken. 

In line 146 and line 234, the sensor is using ,loop=hass.loop, which should be removed in order for the sensor working again in a proper way in HA. For as far I can see, the 10 second update cycle is still working.

Still not into github to make a request, so hopefully you don't mind passing the info like this. 
And as always, thanks for the initial effort to make this sensor possible.

**Comment by kloknibor** [comment]
Sorry didn't see your comment earlier, you are correct, just removing seems to solve it. Thanks!
