### ISSUE TITLE
Edited sensor.py and update_ha_state

### ISSUE THREAD

**Issue by ebk71** [kloknibor/MasterVoltXS#9]
I have edited the sensor.py script to correct some issues with coming deprecated "functions". I'm a complete newbie. 
[sensor2024-05-06.zip](https://github.com/kloknibor/MasterVoltXS/files/15219234/sensor2024-05-06.zip)

But still have this error in the home-assistant.log:
WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.wtot_solar (<class 'custom_components.MasterVoltXS.sensor.SunMasterXSSensorEnergy'>) is using self.async_update_ha_state(), without enabling force_refresh. Instead it should use self.async_write_ha_state(), please create a bug report at https://www.home-assistant.io/components/MastervoltXS/issues

Thanks for the script, there is not a lot to find for a Mastervolt.

**Comment by muppet99** [comment]
Did you see my pull? Maybe it also contains some code you can use:

[https://github.com/kloknibor/MasterVoltXS/pull/8/commits/51141b98395b5d66a922b923fe8462d5fb080612]
